# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc93280d11077696556b797f873c4b4f8d0a836c5d65f196f17b371a117889167bc0a9cdb084cfd3a09f953778809763c5069158a8b077fa95180763ba7fbf1e

test:
  secret_key_base: f30e657c7be1d3f0d6ab4bee354c50406f39f2165d74ec262cd78a336e9284bf9c159e446ec895284e47b50f3eccf13ff950470d061fa92b33def890d11ebe01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
